# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20170331_0049'),
        ('blog', '0005_auto_20170330_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(to='topic.Topic'),
        ),
    ]
