# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_auto_20170330_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('posts', models.ManyToManyField(to='blog.Post')),
            ],
        ),
    ]
