# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='posts',
            field=models.ManyToManyField(related_name='topic_posts', to='blog.Post'),
        ),
    ]
